version: '2'

services:
  db:
    image: postgres:latest
    ports:
      - "127.0.0.1:5433:5432"
    container_name: db
    environment:
      - POSTGRES_DB=my-db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin